version: '3'

services:
    web:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - db
        volumes:
            - .:/code/
        command: python manage.py runserver 0.0.0.0:8000

    bot:
        build: .
        depends_on:
            - db
        volumes:
            - .:/code/
        command: python manage.py bot

    db:
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=r45uDfbh32QAHDbAF
            - POSTGRES_USER=django_admin
            - POSTGRES_DB=spb_beer
        volumes:
            - spb_beer_bot_pg:/var/lib/postgresql/data

volumes:
    spb_beer_bot_pg:
        external: true
