# Generated by Django 4.1.6 on 2023-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='Адрес')),
                ('place_type', models.CharField(max_length=300, null=True, verbose_name='Тип заведение')),
                ('social_media_link', models.CharField(max_length=300, null=True, verbose_name='Соцсеть')),
                ('working_hours', models.CharField(max_length=300, null=True, verbose_name='Рабочие часы')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фотография')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('city', models.CharField(default='Санкт-Петербург', max_length=300, null=True, verbose_name='Город')),
                ('ymaps', models.CharField(max_length=300, null=True, verbose_name='Yandex Maps')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
            ],
        ),
    ]
