# Generated by Django 4.1.6 on 2023-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
