# Generated by Django 4.1.6 on 2023-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='name',
            field=models.CharField(default='Название', max_length=300, verbose_name='Название'),
        ),
    ]
