# Generated by Django 4.1.6 on 2023-05-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_pub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='distance',
        ),
    ]
