# Generated by Django 4.1.6 on 2023-05-10 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_pub_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pub',
            options={'ordering': ['created_at'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.AddField(
            model_name='pub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
